### ISSUE TITLE
Training command and training time

### ISSUE THREAD

**Issue by LeonHLJ** [HDETR/H-Detic-LVIS#1]
Thanks for your wonderful work. 

- I'm confused about the training command, specifically, the arguments of '--resume' and '--eval-only'  are right? 
- Could you provide the training time of Swin-Base and Swin-Large H-deformable DETR on LVIS v1.0?

**Comment by PkuRainBow** [comment]
@hardyho Please help to answer the first question.

For your second concern, we have optimized the original implementation of HDETR and we plan to release the optimized implementation soon, which only brings a slight extra training time (~5%).

**Comment by hardyho** [comment]
Thanks for your reminder, I just updated the README.md and the training command should be correct now. For the second question, the time may be different depending on GPU. We run our experiment on 8 V100 GPUs and it takes about 6 days for Swin-Base and Swin-Large experiments.

**Comment by LeonHLJ** [comment]
Thanks for your prompt response.
